### ISSUE TITLE
機関誌「地図」最新号目次を更新する

### ISSUE THREAD

**Issue by TArahori** [japancartographersassociation/www#21]
機関誌「地図」最新号目次を55-4に更新する。
広報委員会メーリングリストに添付されているExcelファイルの内容に更新する。

**Comment by mapconcierge** [comment]
＞ @TArahori 変更内容もここに記載お願いします！

**Comment by TArahori** [comment]
具体的な変更内容を記載いたします。
55-4となっていますが、正しくは「53-4」です。申し訳ありません。
よろしくお願いいたします。

更新ページ：トップページメニュー→機関誌→最新号目次：目次ページ　http://jcaci.org/table.html
※上から論文のカテゴリー，タイトル，著者名の順に記載しています．

Vol.53 No.4 (通巻212号) 2015年
【巻頭言】 
ICC 2019東京大会招致の意義
森田　喬
【総説・展望】
漢字文化圏における地名標準化
田邉　裕
　キーワード：地名，漢字，翻字，翻訳，標準化
【資料・添付地図解説】
陸海シームレス陰陽図の地図利用 －日本周辺の陸域と海域の地形図－
秋山幸秀・酒井拓也・大森康至・熊谷　清
　キーワード：地形，地球表面，日本地図学会2014定期大会，シームレス，プレートテクトニクス
【定期大会】
地図資料の収集・整理・保存・活用についての一提言 －文書館・地図センターの実践を通して－
増山聖子
【定期大会】
2015年度定期大会報告　
佐藤　潤・鎌田高造・若林芳樹・増山聖子・森田　喬・鈴木厚志・中村和彦・藤田秀之・有川正俊・田中　圭・上田秀敏
【書評・紹介】
明治・大正・昭和　絵葉書地図コレクション －地図に刻まれた近代日本－
佐藤　潤　
日本列島　水をとったら？（ビジュアル地形案内1～3）
佐藤　潤
1945・昭和20年　米軍に撮影された日本　－空中写真に遺された戦争と空襲の証言－
佐藤　潤
【特別会員名簿】
【年間総目次】
【学会記事】
【添付地図】
The Earth Surface Topographic Map (IN-YOU-ZU)

**Comment by mapconcierge** [comment]
THX ＞ @TArahori

**Comment by mapconcierge** [comment]
修正しました！

http://jcaci.org/table.html

![2016-02-29 10 19 43](https://cloud.githubusercontent.com/assets/416977/13383523/18bccfa8-dece-11e5-9d4b-e8d4dfcfe93e.png)

**Comment by mapconcierge** [comment]
閉じま〜す！
