### ISSUE TITLE
役員・評議員ページの修正

### ISSUE THREAD

**Issue by TArahori** [japancartographersassociation/www#23]
総務委員会「委員」になっている田中宏明さんを「担当常任委員」の欄に入れる。
「常任委員」の欄に田中宏明さんを新しく追加する。

**Comment by mapconcierge** [comment]
対応しました！
https://github.com/japancartographersassociation/www_jcaci_org/commit/72d177730c8ba442045673dba83a6cc51ca1f86c

**Comment by mapconcierge** [comment]
![2016-02-27 16 23 13](https://cloud.githubusercontent.com/assets/416977/13371637/7eca421e-dd6e-11e5-99d9-116a9996c7bc.png)

**Comment by mapconcierge** [comment]
http://jcaci.org/organization.html
![2016-02-27 16 23 06](https://cloud.githubusercontent.com/assets/416977/13371643/8631c5cc-dd6e-11e5-981e-1f5e15cda073.png)

**Comment by mapconcierge** [comment]
＞ @TArahori くん
今後、Issue として上げるときには、なるべくどのページなのかなど、具体的な情報も追加してもらえると、Issue の内容が理解しやすくなるので、依頼者の依頼内容を具体化する作業お願いします！
